name: Docker Build and push

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN}}
          registry: docker.pkg.github.com
          repository: tejasvedagiri/stockapi/stockapi
          dockerfile: Dockerfile
          tag_with_ref: true
          tag_with_sha: true
